name: parking_admin
description: "Desktop admin app for parking"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  parking_shared_logic:
    path: '../parking_shared_logic'
  parking_shared_ui:
    path: '../parking_shared_ui'
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true