name: parking_shared_logic
description: A shared library for models, repositories, enums and utils
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  uuid: ^4.4.2
  http: ^1.1.0
  intl: ^0.20.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
