name: parking_shared_ui
description: "Shared ui for parking user and parking admin"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  parking_shared_logic:
    path: '../parking_shared_logic'
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true